server:
  port: 8090
  servlet:
    context-path: /net

spring:
  datasource:
    username: outUser
    password: NoDownMeng@154&Wan
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:mysql://47.102.199.91:3306/sessionkey?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    hikari:
      max-lifetime: 60000
      maximum-pool-size: 10
      idle-timeout: 60000
      connection-timeout: 60000
      validation-timeout: 3000
      LoginTimeout: 60000

## Mybatis 配置
# 配置为 com.pancm.bean 指向实体类包路径。
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.nethomework.jwt.domain
